const products=[
{name:'Slider Station',price:'$459+',serves:'20–25',cat:'lunch',diet:'DF/GF options',img:'linear-gradient(135deg,#7a2a18,#f5a623)'},
{name:'Taco Station',price:'$499+',serves:'20–25',cat:'hot',diet:'GF / vegan add-ons',img:'linear-gradient(135deg,#e83e8c,#ffcf33)'},
{name:'Poke Bowl Station',price:'$499+',serves:'20–25',cat:'fresh',diet:'DF / GF friendly',img:'linear-gradient(135deg,#0f8b8d,#f4d35e)'},
{name:'Bowl Bundle',price:'$979+',serves:'40–50',cat:'large',diet:'Dietaries covered',img:'linear-gradient(135deg,#3d2c1f,#e83e8c)'},
{name:'100 Party Pack',price:'$2,069+',serves:'100',cat:'large',diet:'DF/GF/Vegan',img:'linear-gradient(135deg,#111,#d2a679)'},
{name:'Dipper Donut Kit',price:'$199+',serves:'10–15',cat:'sweet',diet:'GF donuts add-on',img:'linear-gradient(135deg,#ff78b5,#6b3f2a)'}];
const qs=s=>document.querySelector(s); let city='Auckland';
function nav(cls=''){return `<header class="nav ${cls}"><a href="/" class="logo">Cater<span>Station</span></a><button class="hamb">Menu</button><nav><a href="#stations">Stations</a><a href="#how">How it works</a><a href="#delivery">Delivery</a><a href="#faq">FAQs</a><button class="pill city">${city}</button><button class="quote">Get quote</button></nav></header>`}
function cards(filter='all'){return products.filter(p=>filter=='all'||p.cat==filter).map(p=>`<article class="card product" data-name="${p.name}"><div class="photo" style="background:${p.img}"><b>real CaterStation photo placeholder</b></div><div><h3>${p.name}</h3><p>${p.serves} people · ${p.diet}</p><strong>${p.price}</strong></div><button>Quick view</button></article>`).join('')}
function footer(){return `<footer><b>CaterStation</b><p>Auckland & Wellington catering. Prototype only — no checkout.</p><a href="/comparison">Compare concepts</a></footer><div class="toast"></div>`}
function modal(){return `<dialog id="quote"><form method="dialog"><button class="x">×</button><h2>Quick quote request</h2><input placeholder="Work email"><input placeholder="People count"><textarea placeholder="Event notes"></textarea><button>Send prototype request</button></form></dialog>`}
function bind(){document.querySelectorAll('.city').forEach(b=>b.onclick=()=>{city=city=='Auckland'?'Wellington':'Auckland';render()});document.querySelectorAll('.quote').forEach(b=>b.onclick=()=>qs('#quote').showModal());document.querySelectorAll('.hamb').forEach(b=>b.onclick=()=>document.body.classList.toggle('menu'));document.querySelectorAll('.product').forEach(c=>c.onclick=()=>{qs('.toast').textContent=`${c.dataset.name}: added to prototype shortlist`;qs('.toast').classList.add('show');setTimeout(()=>qs('.toast').classList.remove('show'),1800)});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{qs('#grid').innerHTML=cards(b.dataset.filter);bind()})}
function home(){return `${nav()}<main class="dash"><section class="hero"><p class="eyebrow">Prototype lab</p><h1>Three new CaterStation homepage directions.</h1><p>Research found a bold, fun brand with strong product photography and useful FAQ content, but product discovery currently asks busy office organisers to infer headcount, dietaries, delivery confidence and quote-vs-order paths from scattered sections.</p></section><section class="concepts">${['Corporate Ordering Machine','Big Food Reveal','Build Your Feed'].map((t,i)=>`<a class="concept c${i+1}" href="/concept-${['one','two','three'][i]}"><span>Concept ${i+1}</span><h2>${t}</h2><p>${['Headcount-first conversion flow for office buyers.','Editorial box-opening story with oversized brand moments.','Interactive recommender for occasions, dietaries and group sizes.'][i]}</p></a>`).join('')}</section><a class="biglink" href="/comparison">Open scoring comparison →</a></main>${footer()}${modal()}`}
function one(){return `${nav('machine')}<main class="machine"><section class="split hero"><div><p class="eyebrow">Office catering made obvious</p><h1>Feed the team without becoming the catering department.</h1><p>Choose city, occasion and headcount. We’ll point you to stations that arrive hot, ready to serve and easy to expense.</p><div class="actions"><button>Order online</button><button class="quote">Get a quote</button></div></div><div class="planner"><h2>What are you feeding?</h2>${['Team lunch','Staff celebration','Client event','50+ people','I’m not sure'].map(x=>`<button>${x}</button>`).join('')}<label>How many people? <input type="range" min="10" max="150" value="35" oninput="this.nextElementSibling.textContent=this.value+' people'"><b>35 people</b></label></div></section><section class="trust"><b>Delivered hot</b><b>Invoice payment</b><b>Dietary labels</b><b>${city} delivery</b></section><section id="stations"><h2>Shop by headcount</h2><div class="filters"><button data-filter="all">All</button><button data-filter="lunch">20–25</button><button data-filter="large">40+</button><button data-filter="sweet">Dessert</button></div><div id="grid" class="grid">${cards()}</div></section><section id="how" class="steps"><h2>How it works</h2><ol><li>Pick your station and delivery window.</li><li>Food arrives sealed, hot and labelled.</li><li>Open the box, set out the station and let everyone build their plate.</li></ol></section>${info()}${footer()}${modal()}<div class="sticky"><button>Order online</button><button class="quote">Quote</button></div></main>`}
function two(){return `${nav('reveal')}<main class="reveal"><section class="boxhero"><div class="box">OPEN<br>THE<br>BOX</div><h1>It’s coming in hot.</h1><p>The CaterStation moment: cardboard opens, colour lands, the team gathers.</p></section><section class="story"><article><h2>1. The box arrives.</h2><p>Ready-to-serve stations delivered across ${city}.</p></article><article><h2>2. The station unfolds.</h2><p>Tacos, sliders, bowls and donuts laid out for build-your-own energy.</p></article><article><h2>3. Everyone talks.</h2><p>Generous food that makes the organiser look good.</p></article></section><section id="stations"><h2>Revealed favourites</h2><div class="masonry">${cards('all')}</div></section>${info()}${footer()}${modal()}</main>`}
function three(){return `${nav('feed')}<main class="feed"><section class="hero"><h1>Build your feed.</h1><p>Answer four quick prompts and get a CaterStation combination for your team.</p><div class="wizard"><select id="people"><option>25</option><option>50</option><option>100</option></select><select id="occasion"><option>Team lunch</option><option>Client event</option><option>Celebration</option></select><label><input type="checkbox" id="vegan"> Vegan needed</label><label><input type="checkbox" id="gf"> Gluten friendly needed</label><button id="rec">Show my feed</button></div><div id="result" class="result">Recommended: Taco Station + Dipper Donut Kit for a generous 25-person lunch.</div></section><section id="stations"><h2>Browse by craving</h2><div class="filters"><button data-filter="hot">Hot</button><button data-filter="fresh">Fresh</button><button data-filter="sweet">Sweet</button><button data-filter="large">Large events</button></div><div id="grid" class="grid">${cards()}</div></section>${info()}${footer()}${modal()}</main>`}
function info(){return `<section id="delivery" class="info"><h2>Confidence before checkout</h2><div><p><b>Delivery:</b> Auckland and Wellington menus with delivery windows and postcode checks.</p><p><b>Heat:</b> sealed meats stay piping hot up to 1 hour; opened food serves well for 45–60 minutes.</p><p><b>Dietaries:</b> GF-friendly, DF, vegan and halal-sourced options are clearly labelled; allergy caveats stay visible.</p><p><b>Corporate:</b> invoice payment available at checkout for office expenses.</p></div></section><section id="faq" class="faq"><h2>Big event?</h2><p>Feeding more than 100? Request a package and we’ll build the right mix of stations, dessert and serveware.</p><button class="quote">Get large-event quote</button></section>`}
function comparison(){let names=['Corporate Ordering Machine','Big Food Reveal','Build Your Feed'];let rows=['Brand distinctiveness','Ease of ordering','Corporate conversion potential','Product discoverability','Mobile usability','Emotional impact','Shopify implementation difficulty','Long-term maintainability'];return `${nav()}<main class="dash"><h1>Concept comparison</h1><table><thead><tr><th>Criteria</th>${names.map(n=>`<th>${n}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${r}</td><td>${[7,10,9,8,9,7,5,9][i]}</td><td>${[10,6,7,7,7,10,7,6][i]}</td><td>${[8,8,8,10,8,8,6,7][i]}</td></tr>`).join('')}</tbody></table><section class="info"><h2>Recommendation</h2><p>Safest commercial option: Concept 1. Boldest brand option: Concept 2. Best hybrid: Concept 1’s buying architecture with Concept 2’s box-reveal visual moments and Concept 3’s recommender module.</p></section></main>${footer()}${modal()}`}
function render(){let p=location.pathname;app.innerHTML=p.includes('concept-one')?one():p.includes('concept-two')?two():p.includes('concept-three')?three():p.includes('comparison')?comparison():home();bind(); let rec=qs('#rec'); if(rec) rec.onclick=()=>qs('#result').textContent=`Recommended: ${qs('#people').value>50?'100 Party Pack + donuts':'Bowl Bundle + sliders'} for ${qs('#occasion').value.toLowerCase()} in ${city}${qs('#vegan').checked?' with vegan add-ons':''}${qs('#gf').checked?' and gluten-friendly extras':''}.`;}
render();
